// [atlas, task, milestone_number, milestone_value, is_unknown, is_final_milestone, rarity, fragment_reward]
const MILESTONES = [
  // Rekindled Flames — Log in for X day(s)
  ['Rekindled Flames','Log in for X day(s)',1,'7',0,0,'Rare','Rare Puzzle Fragment'],
  ['Rekindled Flames','Log in for X day(s)',2,'30',0,0,'Rare','Rare Puzzle Fragment'],
  ['Rekindled Flames','Log in for X day(s)',3,'60',0,0,'Epic','Epic Puzzle Fragment'],
  ['Rekindled Flames','Log in for X day(s)',4,'90',0,0,'Epic','Epic Puzzle Fragment'],
  ['Rekindled Flames','Log in for X day(s)',5,'150',0,0,'Epic','Epic Puzzle Fragment'],
  ['Rekindled Flames','Log in for X day(s)',6,'200',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Rekindled Flames','Log in for X day(s)',7,null,1,0,null,null],
  // Rekindled Flames — Produce X of any resource in the City
  ['Rekindled Flames','Produce X of any resource in the City',1,'3,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Rekindled Flames','Produce X of any resource in the City',2,'10,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Rekindled Flames','Produce X of any resource in the City',3,'30,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Rekindled Flames','Produce X of any resource in the City',4,'50,000,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Rekindled Flames','Produce X of any resource in the City',5,'100,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Rekindled Flames','Produce X of any resource in the City',6,'500,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Rekindled Flames','Produce X of any resource in the City',7,'1,000,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Rekindled Flames','Produce X of any resource in the City',8,'5,000,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Rekindled Flames','Produce X of any resource in the City',9,'10,000,000,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Rekindled Flames — Publish Chief Orders X time(s)
  ['Rekindled Flames','Publish Chief Orders X time(s)',1,'10',0,0,'Rare','Rare Puzzle Fragment'],
  ['Rekindled Flames','Publish Chief Orders X time(s)',2,'30',0,0,'Rare','Rare Puzzle Fragment'],
  ['Rekindled Flames','Publish Chief Orders X time(s)',3,'50',0,0,'Rare','Rare Puzzle Fragment'],
  ['Rekindled Flames','Publish Chief Orders X time(s)',4,'100',0,0,'Epic','Epic Puzzle Fragment'],
  ['Rekindled Flames','Publish Chief Orders X time(s)',5,'200',0,0,'Epic','Epic Puzzle Fragment'],
  ['Rekindled Flames','Publish Chief Orders X time(s)',6,'400',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Rekindled Flames','Publish Chief Orders X time(s)',7,'800',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Rekindled Flames','Publish Chief Orders X time(s)',8,'1,600',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Rekindled Flames','Publish Chief Orders X time(s)',9,null,1,0,null,null],
  // Rekindled Flames — Finish X Intel Mission(s)
  ['Rekindled Flames','Finish X Intel Mission(s)',1,'150',0,0,'Rare','Rare Puzzle Fragment'],
  ['Rekindled Flames','Finish X Intel Mission(s)',2,'300',0,0,'Rare','Rare Puzzle Fragment'],
  ['Rekindled Flames','Finish X Intel Mission(s)',3,'600',0,0,'Rare','Rare Puzzle Fragment'],
  ['Rekindled Flames','Finish X Intel Mission(s)',4,'1,200',0,0,'Epic','Epic Puzzle Fragment'],
  ['Rekindled Flames','Finish X Intel Mission(s)',5,'2,400',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Rekindled Flames','Finish X Intel Mission(s)',6,'4,800',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Rekindled Flames','Finish X Intel Mission(s)',7,'7,200',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Rekindled Flames','Finish X Intel Mission(s)',8,null,1,0,null,null],
  // Rekindled Flames — Gather X resources
  ['Rekindled Flames','Gather X resources',1,'3,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Rekindled Flames','Gather X resources',2,'10,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Rekindled Flames','Gather X resources',3,'30,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Rekindled Flames','Gather X resources',4,'50,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Rekindled Flames','Gather X resources',5,'100,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Rekindled Flames','Gather X resources',6,'500,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Rekindled Flames','Gather X resources',7,'1,000,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Rekindled Flames','Gather X resources',8,'5,000,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Rekindled Flames','Gather X resources',9,'10,000,000,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Rekindled Flames — Reach Furnace Lv. X
  ['Rekindled Flames','Reach Furnace Lv. X',1,'7',0,0,'Rare','Rare Puzzle Fragment'],
  ['Rekindled Flames','Reach Furnace Lv. X',2,'10',0,0,'Rare','Rare Puzzle Fragment'],
  ['Rekindled Flames','Reach Furnace Lv. X',3,'13',0,0,'Rare','Rare Puzzle Fragment'],
  ['Rekindled Flames','Reach Furnace Lv. X',4,'16',0,0,'Epic','Epic Puzzle Fragment'],
  ['Rekindled Flames','Reach Furnace Lv. X',5,'18',0,0,'Epic','Epic Puzzle Fragment'],
  ['Rekindled Flames','Reach Furnace Lv. X',6,'20',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Rekindled Flames','Reach Furnace Lv. X',7,'22',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Rekindled Flames','Reach Furnace Lv. X',8,'24',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Rekindled Flames','Reach Furnace Lv. X',9,'26',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Rekindled Flames','Reach Furnace Lv. X',10,'30',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Song of Heroes — Own X Hero(es)
  ['Song of Heroes','Own X Hero(es)',1,'3',0,0,'Rare','Rare Puzzle Fragment'],
  ['Song of Heroes','Own X Hero(es)',2,'5',0,0,'Rare','Rare Puzzle Fragment'],
  ['Song of Heroes','Own X Hero(es)',3,'7',0,0,'Rare','Rare Puzzle Fragment'],
  ['Song of Heroes','Own X Hero(es)',4,'9',0,0,'Epic','Epic Puzzle Fragment'],
  ['Song of Heroes','Own X Hero(es)',5,'12',0,0,'Epic','Epic Puzzle Fragment'],
  ['Song of Heroes','Own X Hero(es)',6,'14',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Song of Heroes','Own X Hero(es)',7,'16',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Song of Heroes','Own X Hero(es)',8,'18',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Song of Heroes','Own X Hero(es)',9,'20',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Song of Heroes — Use Advanced Recruitment X time(s)
  ['Song of Heroes','Use Advanced Recruitment X time(s)',1,'50',0,0,'Rare','Rare Puzzle Fragment'],
  ['Song of Heroes','Use Advanced Recruitment X time(s)',2,'200',0,0,'Rare','Rare Puzzle Fragment'],
  ['Song of Heroes','Use Advanced Recruitment X time(s)',3,'400',0,0,'Rare','Rare Puzzle Fragment'],
  ['Song of Heroes','Use Advanced Recruitment X time(s)',4,'600',0,0,'Epic','Epic Puzzle Fragment'],
  ['Song of Heroes','Use Advanced Recruitment X time(s)',5,'1,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Song of Heroes','Use Advanced Recruitment X time(s)',6,'1,600',0,0,'Epic','Epic Puzzle Fragment'],
  ['Song of Heroes','Use Advanced Recruitment X time(s)',7,'2,300',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Song of Heroes','Use Advanced Recruitment X time(s)',8,'3,200',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Song of Heroes','Use Advanced Recruitment X time(s)',9,'4,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Song of Heroes — Use Epic Recruitment X time(s)
  ['Song of Heroes','Use Epic Recruitment X time(s)',1,'25',0,0,'Rare','Rare Puzzle Fragment'],
  ['Song of Heroes','Use Epic Recruitment X time(s)',2,'50',0,0,'Rare','Rare Puzzle Fragment'],
  ['Song of Heroes','Use Epic Recruitment X time(s)',3,'100',0,0,'Rare','Rare Puzzle Fragment'],
  ['Song of Heroes','Use Epic Recruitment X time(s)',4,'200',0,0,'Epic','Epic Puzzle Fragment'],
  ['Song of Heroes','Use Epic Recruitment X time(s)',5,'400',0,0,'Epic','Epic Puzzle Fragment'],
  ['Song of Heroes','Use Epic Recruitment X time(s)',6,'600',0,0,'Epic','Epic Puzzle Fragment'],
  ['Song of Heroes','Use Epic Recruitment X time(s)',7,'1,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Song of Heroes','Use Epic Recruitment X time(s)',8,'1,500',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Song of Heroes','Use Epic Recruitment X time(s)',9,'2,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Song of Heroes','Use Epic Recruitment X time(s)',10,'2,500',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Song of Heroes — Upgrade an Epic Hero to X-Star
  ['Song of Heroes','Upgrade an Epic Hero to X-Star',1,'6 (1★)',0,0,'Rare','Rare Puzzle Fragment'],
  ['Song of Heroes','Upgrade an Epic Hero to X-Star',2,'12 (2★)',0,0,'Rare','Rare Puzzle Fragment'],
  ['Song of Heroes','Upgrade an Epic Hero to X-Star',3,'18 (3★)',0,0,'Rare','Rare Puzzle Fragment'],
  ['Song of Heroes','Upgrade an Epic Hero to X-Star',4,'24 (4★)',0,0,'Epic','Epic Puzzle Fragment'],
  ['Song of Heroes','Upgrade an Epic Hero to X-Star',5,'30 (5★)',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Song of Heroes — Upgrade a Mythic Hero to X-Star
  ['Song of Heroes','Upgrade a Mythic Hero to X-Star',1,'6 (1★)',0,0,'Rare','Rare Puzzle Fragment'],
  ['Song of Heroes','Upgrade a Mythic Hero to X-Star',2,'12 (2★)',0,0,'Rare','Rare Puzzle Fragment'],
  ['Song of Heroes','Upgrade a Mythic Hero to X-Star',3,'18 (3★)',0,0,'Rare','Rare Puzzle Fragment'],
  ['Song of Heroes','Upgrade a Mythic Hero to X-Star',4,'24 (4★)',0,0,'Epic','Epic Puzzle Fragment'],
  ['Song of Heroes','Upgrade a Mythic Hero to X-Star',5,'30 (5★)',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Song of Heroes — Clear Exploration Stage X
  ['Song of Heroes','Clear Exploration Stage X',1,'150',0,0,'Rare','Rare Puzzle Fragment'],
  ['Song of Heroes','Clear Exploration Stage X',2,'175',0,0,'Rare','Rare Puzzle Fragment'],
  ['Song of Heroes','Clear Exploration Stage X',3,'200',0,0,'Rare','Rare Puzzle Fragment'],
  ['Song of Heroes','Clear Exploration Stage X',4,'225',0,0,'Epic','Epic Puzzle Fragment'],
  ['Song of Heroes','Clear Exploration Stage X',5,'250',0,0,'Epic','Epic Puzzle Fragment'],
  ['Song of Heroes','Clear Exploration Stage X',6,'275',0,0,'Epic','Epic Puzzle Fragment'],
  ['Song of Heroes','Clear Exploration Stage X',7,'300',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Song of Heroes','Clear Exploration Stage X',8,'325',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Song of Heroes','Clear Exploration Stage X',9,'350',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Song of Heroes','Clear Exploration Stage X',10,'375',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Song of Heroes','Clear Exploration Stage X',11,'400',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Song of Heroes','Clear Exploration Stage X',12,'425',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Song of Heroes','Clear Exploration Stage X',13,'450',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Song of Heroes','Clear Exploration Stage X',14,'475',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Song of Heroes','Clear Exploration Stage X',15,'500',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Explore the World — Train X Lv. 10+ Troop(s)
  ['Explore the World','Train X Lv. 10+ Troop(s)',1,'10,000 (lv5)',0,0,'Rare','Rare Puzzle Fragment'],
  ['Explore the World','Train X Lv. 10+ Troop(s)',2,'30,000 (lv6)',0,0,'Rare','Rare Puzzle Fragment'],
  ['Explore the World','Train X Lv. 10+ Troop(s)',3,'50,000 (lv7)',0,0,'Rare','Rare Puzzle Fragment'],
  ['Explore the World','Train X Lv. 10+ Troop(s)',4,'100,000 (lv8)',0,0,'Epic','Epic Puzzle Fragment'],
  ['Explore the World','Train X Lv. 10+ Troop(s)',5,'150,000 (lv9)',0,0,'Epic','Epic Puzzle Fragment'],
  ['Explore the World','Train X Lv. 10+ Troop(s)',6,'200,000 (lv10)',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Explore the World','Train X Lv. 10+ Troop(s)',7,'250,000 (lv10)',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Explore the World','Train X Lv. 10+ Troop(s)',8,'300,000 (lv10)',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Explore the World','Train X Lv. 10+ Troop(s)',9,'400,000 (lv10)',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Explore the World','Train X Lv. 10+ Troop(s)',10,'500,000 (lv10)',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Explore the World — Defeat X Beasts
  ['Explore the World','Defeat X Beasts',1,'50',0,0,'Rare','Rare Puzzle Fragment'],
  ['Explore the World','Defeat X Beasts',2,'100',0,0,'Rare','Rare Puzzle Fragment'],
  ['Explore the World','Defeat X Beasts',3,'300',0,0,'Rare','Rare Puzzle Fragment'],
  ['Explore the World','Defeat X Beasts',4,'500',0,0,'Epic','Epic Puzzle Fragment'],
  ['Explore the World','Defeat X Beasts',5,'800',0,0,'Epic','Epic Puzzle Fragment'],
  ['Explore the World','Defeat X Beasts',6,'1,200',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Explore the World','Defeat X Beasts',7,'1,800',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Explore the World','Defeat X Beasts',8,'2,400',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Explore the World','Defeat X Beasts',9,'3,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Explore the World — Call rally on Polar Terror (Lv. 8+) X time(s)
  ['Explore the World','Call rally on Polar Terror (Lv. 8+) X time(s)',1,'1',0,0,'Rare','Rare Puzzle Fragment'],
  ['Explore the World','Call rally on Polar Terror (Lv. 8+) X time(s)',2,'2',0,0,'Rare','Rare Puzzle Fragment'],
  ['Explore the World','Call rally on Polar Terror (Lv. 8+) X time(s)',3,'3',0,0,'Epic','Epic Puzzle Fragment'],
  ['Explore the World','Call rally on Polar Terror (Lv. 8+) X time(s)',4,'4',0,0,'Epic','Epic Puzzle Fragment'],
  ['Explore the World','Call rally on Polar Terror (Lv. 8+) X time(s)',5,'5',0,0,'Epic','Epic Puzzle Fragment'],
  ['Explore the World','Call rally on Polar Terror (Lv. 8+) X time(s)',6,'6',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Explore the World','Call rally on Polar Terror (Lv. 8+) X time(s)',7,'7',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Explore the World','Call rally on Polar Terror (Lv. 8+) X time(s)',8,'8',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Explore the World — Join X Polar Terror rallies
  ['Explore the World','Join X Polar Terror rallies',1,'30',0,0,'Rare','Rare Puzzle Fragment'],
  ['Explore the World','Join X Polar Terror rallies',2,'60',0,0,'Rare','Rare Puzzle Fragment'],
  ['Explore the World','Join X Polar Terror rallies',3,'120',0,0,'Epic','Epic Puzzle Fragment'],
  ['Explore the World','Join X Polar Terror rallies',4,'240',0,0,'Epic','Epic Puzzle Fragment'],
  ['Explore the World','Join X Polar Terror rallies',5,'500',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Explore the World','Join X Polar Terror rallies',6,'1,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Explore the World','Join X Polar Terror rallies',7,'2,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Explore the World','Join X Polar Terror rallies',8,'3,500',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Explore the World','Join X Polar Terror rallies',9,'5,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Explore the World — Heal X injured soldiers
  ['Explore the World','Heal X injured soldiers',1,'10,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Explore the World','Heal X injured soldiers',2,'20,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Explore the World','Heal X injured soldiers',3,'40,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Explore the World','Heal X injured soldiers',4,'60,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Explore the World','Heal X injured soldiers',5,'100,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Explore the World','Heal X injured soldiers',6,'150,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Explore the World','Heal X injured soldiers',7,'200,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Explore the World','Heal X injured soldiers',8,'270,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Explore the World','Heal X injured soldiers',9,'350,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Explore the World','Heal X injured soldiers',10,'450,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Explore the World — Participate in Bear Hunt X time(s)
  ['Explore the World','Participate in Bear Hunt X time(s)',1,'5',0,0,'Rare','Rare Puzzle Fragment'],
  ['Explore the World','Participate in Bear Hunt X time(s)',2,'10',0,0,'Epic','Epic Puzzle Fragment'],
  ['Explore the World','Participate in Bear Hunt X time(s)',3,'15',0,0,'Epic','Epic Puzzle Fragment'],
  ['Explore the World','Participate in Bear Hunt X time(s)',4,'20',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Explore the World','Participate in Bear Hunt X time(s)',5,'25',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Explore the World','Participate in Bear Hunt X time(s)',6,'30',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Explore the World','Participate in Bear Hunt X time(s)',7,'40',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Explore the World','Participate in Bear Hunt X time(s)',8,'50',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Daybreak Island — Upgrade Tree of Life to Lv. X
  ['Daybreak Island','Upgrade Tree of Life to Lv. X',1,'1',0,0,'Rare','Rare Puzzle Fragment'],
  ['Daybreak Island','Upgrade Tree of Life to Lv. X',2,'2',0,0,'Rare','Rare Puzzle Fragment'],
  ['Daybreak Island','Upgrade Tree of Life to Lv. X',3,'3',0,0,'Rare','Rare Puzzle Fragment'],
  ['Daybreak Island','Upgrade Tree of Life to Lv. X',4,'4',0,0,'Epic','Epic Puzzle Fragment'],
  ['Daybreak Island','Upgrade Tree of Life to Lv. X',5,'5',0,0,'Epic','Epic Puzzle Fragment'],
  ['Daybreak Island','Upgrade Tree of Life to Lv. X',6,'6',0,0,'Epic','Epic Puzzle Fragment'],
  ['Daybreak Island','Upgrade Tree of Life to Lv. X',7,'7',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Upgrade Tree of Life to Lv. X',8,'8',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Upgrade Tree of Life to Lv. X',9,'9',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Upgrade Tree of Life to Lv. X',10,'10',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Daybreak Island — Help ally care for Tree of Life X time(s)
  ['Daybreak Island','Help ally care for Tree of Life X time(s)',1,'10',0,0,'Rare','Rare Puzzle Fragment'],
  ['Daybreak Island','Help ally care for Tree of Life X time(s)',2,'20',0,0,'Rare','Rare Puzzle Fragment'],
  ['Daybreak Island','Help ally care for Tree of Life X time(s)',3,'40',0,0,'Rare','Rare Puzzle Fragment'],
  ['Daybreak Island','Help ally care for Tree of Life X time(s)',4,'60',0,0,'Epic','Epic Puzzle Fragment'],
  ['Daybreak Island','Help ally care for Tree of Life X time(s)',5,'100',0,0,'Epic','Epic Puzzle Fragment'],
  ['Daybreak Island','Help ally care for Tree of Life X time(s)',6,'200',0,0,'Epic','Epic Puzzle Fragment'],
  ['Daybreak Island','Help ally care for Tree of Life X time(s)',7,'400',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Help ally care for Tree of Life X time(s)',8,'800',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Help ally care for Tree of Life X time(s)',9,'1,200',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Help ally care for Tree of Life X time(s)',10,'1,600',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Help ally care for Tree of Life X time(s)',11,'2,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Help ally care for Tree of Life X time(s)',12,'2,400',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Help ally care for Tree of Life X time(s)',13,null,1,0,null,null],
  // Daybreak Island — Increase Daybreak Island Prosperity to X
  ['Daybreak Island','Increase Daybreak Island Prosperity to X',1,'1,200',0,0,'Rare','Rare Puzzle Fragment'],
  ['Daybreak Island','Increase Daybreak Island Prosperity to X',2,'3,600',0,0,'Rare','Rare Puzzle Fragment'],
  ['Daybreak Island','Increase Daybreak Island Prosperity to X',3,'6,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Daybreak Island','Increase Daybreak Island Prosperity to X',4,'12,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Daybreak Island','Increase Daybreak Island Prosperity to X',5,'24,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Daybreak Island','Increase Daybreak Island Prosperity to X',6,'36,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Daybreak Island','Increase Daybreak Island Prosperity to X',7,'48,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Increase Daybreak Island Prosperity to X',8,'60,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Increase Daybreak Island Prosperity to X',9,'72,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Increase Daybreak Island Prosperity to X',10,'84,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Increase Daybreak Island Prosperity to X',11,'96,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Increase Daybreak Island Prosperity to X',12,'108,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Increase Daybreak Island Prosperity to X',13,'120,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Daybreak Island — Own X type(s) of Mythic decorations
  ['Daybreak Island','Own X type(s) of Mythic decorations',1,'1',0,0,'Rare','Rare Puzzle Fragment'],
  ['Daybreak Island','Own X type(s) of Mythic decorations',2,'2',0,0,'Rare','Rare Puzzle Fragment'],
  ['Daybreak Island','Own X type(s) of Mythic decorations',3,'3',0,0,'Rare','Rare Puzzle Fragment'],
  ['Daybreak Island','Own X type(s) of Mythic decorations',4,'4',0,0,'Epic','Epic Puzzle Fragment'],
  ['Daybreak Island','Own X type(s) of Mythic decorations',5,'5',0,0,'Epic','Epic Puzzle Fragment'],
  ['Daybreak Island','Own X type(s) of Mythic decorations',6,'6',0,0,'Epic','Epic Puzzle Fragment'],
  ['Daybreak Island','Own X type(s) of Mythic decorations',7,'7',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Own X type(s) of Mythic decorations',8,'8',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Own X type(s) of Mythic decorations',9,'9',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Own X type(s) of Mythic decorations',10,'10',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Own X type(s) of Mythic decorations',11,'12',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Own X type(s) of Mythic decorations',12,'14',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Own X type(s) of Mythic decorations',13,'16',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Own X type(s) of Mythic decorations',14,'18',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Daybreak Island','Own X type(s) of Mythic decorations',15,'20',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Tundra Alliance — Make X Alliance Contribution(s)
  ['Tundra Alliance','Make X Alliance Contribution(s)',1,'150',0,0,'Rare','Rare Puzzle Fragment'],
  ['Tundra Alliance','Make X Alliance Contribution(s)',2,'300',0,0,'Rare','Rare Puzzle Fragment'],
  ['Tundra Alliance','Make X Alliance Contribution(s)',3,'500',0,0,'Rare','Rare Puzzle Fragment'],
  ['Tundra Alliance','Make X Alliance Contribution(s)',4,'1,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Tundra Alliance','Make X Alliance Contribution(s)',5,'2,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Tundra Alliance','Make X Alliance Contribution(s)',6,'5,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Tundra Alliance','Make X Alliance Contribution(s)',7,'10,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Tundra Alliance','Make X Alliance Contribution(s)',8,'20,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Tundra Alliance','Make X Alliance Contribution(s)',9,null,1,0,null,null],
  // Tundra Alliance — Take part in Alliance Help X time(s)
  ['Tundra Alliance','Take part in Alliance Help X time(s)',1,'500',0,0,'Rare','Rare Puzzle Fragment'],
  ['Tundra Alliance','Take part in Alliance Help X time(s)',2,'1,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Tundra Alliance','Take part in Alliance Help X time(s)',3,'2,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Tundra Alliance','Take part in Alliance Help X time(s)',4,'5,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Tundra Alliance','Take part in Alliance Help X time(s)',5,'10,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Tundra Alliance','Take part in Alliance Help X time(s)',6,'20,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Tundra Alliance','Take part in Alliance Help X time(s)',7,'30,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Tundra Alliance','Take part in Alliance Help X time(s)',8,'40,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Tundra Alliance','Take part in Alliance Help X time(s)',9,'60,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Tundra Alliance','Take part in Alliance Help X time(s)',10,'80,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Tundra Alliance','Take part in Alliance Help X time(s)',11,'100,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Tundra Alliance — Spend X Alliance Token(s)
  ['Tundra Alliance','Spend X Alliance Token(s)',1,'500,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Tundra Alliance','Spend X Alliance Token(s)',2,'1,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Tundra Alliance','Spend X Alliance Token(s)',3,'2,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Tundra Alliance','Spend X Alliance Token(s)',4,'4,000,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Tundra Alliance','Spend X Alliance Token(s)',5,'8,000,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Tundra Alliance','Spend X Alliance Token(s)',6,'12,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Tundra Alliance','Spend X Alliance Token(s)',7,'16,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Tundra Alliance','Spend X Alliance Token(s)',8,'24,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Tundra Alliance','Spend X Alliance Token(s)',9,'36,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Tundra Alliance','Spend X Alliance Token(s)',10,null,1,0,null,null],
  // Tundra Alliance — Build Alliance Banner for X second(s)
  ['Tundra Alliance','Build Alliance Banner for X second(s)',1,'3,600',0,0,'Rare','Rare Puzzle Fragment'],
  ['Tundra Alliance','Build Alliance Banner for X second(s)',2,'10,800',0,0,'Rare','Rare Puzzle Fragment'],
  ['Tundra Alliance','Build Alliance Banner for X second(s)',3,'21,600',0,0,'Rare','Rare Puzzle Fragment'],
  ['Tundra Alliance','Build Alliance Banner for X second(s)',4,'43,200',0,0,'Epic','Epic Puzzle Fragment'],
  ['Tundra Alliance','Build Alliance Banner for X second(s)',5,'64,800',0,0,'Epic','Epic Puzzle Fragment'],
  ['Tundra Alliance','Build Alliance Banner for X second(s)',6,'129,600',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Tundra Alliance','Build Alliance Banner for X second(s)',7,'259,200',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Tundra Alliance','Build Alliance Banner for X second(s)',8,'300,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Tundra Alliance','Build Alliance Banner for X second(s)',9,'360,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Tundra Alliance','Build Alliance Banner for X second(s)',10,'520,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Tundra Alliance — Claim Alliance Chests X time(s)
  ['Tundra Alliance','Claim Alliance Chests X time(s)',1,'1,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Tundra Alliance','Claim Alliance Chests X time(s)',2,'2,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Tundra Alliance','Claim Alliance Chests X time(s)',3,'3,500',0,0,'Rare','Rare Puzzle Fragment'],
  ['Tundra Alliance','Claim Alliance Chests X time(s)',4,'7,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Tundra Alliance','Claim Alliance Chests X time(s)',5,'12,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Tundra Alliance','Claim Alliance Chests X time(s)',6,'24,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Tundra Alliance','Claim Alliance Chests X time(s)',7,'50,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Tundra Alliance','Claim Alliance Chests X time(s)',8,'100,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Tundra Alliance','Claim Alliance Chests X time(s)',9,null,1,0,null,null],
  // Battlefield epic — Participate in facility fight X time(s)
  ['Battlefield epic','Participate in facility fight X time(s)',1,'10',0,0,'Rare','Rare Puzzle Fragment'],
  ['Battlefield epic','Participate in facility fight X time(s)',2,'25',0,0,'Rare','Rare Puzzle Fragment'],
  ['Battlefield epic','Participate in facility fight X time(s)',3,'50',0,0,'Rare','Rare Puzzle Fragment'],
  ['Battlefield epic','Participate in facility fight X time(s)',4,'100',0,0,'Epic','Epic Puzzle Fragment'],
  ['Battlefield epic','Participate in facility fight X time(s)',5,'200',0,0,'Epic','Epic Puzzle Fragment'],
  ['Battlefield epic','Participate in facility fight X time(s)',6,'400',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Battlefield epic','Participate in facility fight X time(s)',7,'600',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Battlefield epic','Participate in facility fight X time(s)',8,'800',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Battlefield epic','Participate in facility fight X time(s)',9,'1,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Battlefield epic','Participate in facility fight X time(s)',10,'1,500',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Battlefield epic','Participate in facility fight X time(s)',11,null,1,0,null,null],
  // Battlefield epic — Participate in fortress/SH X time(s)
  ['Battlefield epic','Participate in fortress/SH X time(s)',1,'10',0,0,'Rare','Rare Puzzle Fragment'],
  ['Battlefield epic','Participate in fortress/SH X time(s)',2,'25',0,0,'Rare','Rare Puzzle Fragment'],
  ['Battlefield epic','Participate in fortress/SH X time(s)',3,'50',0,0,'Rare','Rare Puzzle Fragment'],
  ['Battlefield epic','Participate in fortress/SH X time(s)',4,'100',0,0,'Epic','Epic Puzzle Fragment'],
  ['Battlefield epic','Participate in fortress/SH X time(s)',5,null,1,0,null,null],
  // Battlefield epic — Kill or injure X troops
  ['Battlefield epic','Kill or injure X troops',1,'3,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Battlefield epic','Kill or injure X troops',2,'5,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Battlefield epic','Kill or injure X troops',3,'10,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Battlefield epic','Kill or injure X troops',4,'20,000,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Battlefield epic','Kill or injure X troops',5,'30,000,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Battlefield epic','Kill or injure X troops',6,'40,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Battlefield epic','Kill or injure X troops',7,'55,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Battlefield epic','Kill or injure X troops',8,'70,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Battlefield epic','Kill or injure X troops',9,'85,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Battlefield epic','Kill or injure X troops',10,'100,000,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Battlefield epic — Obtain X Orichalcum from Frostfire Mine
  ['Battlefield epic','Obtain X Orichalcum from Frostfire Mine',1,'50,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Battlefield epic','Obtain X Orichalcum from Frostfire Mine',2,'100,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Battlefield epic','Obtain X Orichalcum from Frostfire Mine',3,'200,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Battlefield epic','Obtain X Orichalcum from Frostfire Mine',4,'400,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Battlefield epic','Obtain X Orichalcum from Frostfire Mine',5,'800,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Battlefield epic','Obtain X Orichalcum from Frostfire Mine',6,'1,600,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Battlefield epic','Obtain X Orichalcum from Frostfire Mine',7,'3,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Battlefield epic','Obtain X Orichalcum from Frostfire Mine',8,'6,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Battlefield epic','Obtain X Orichalcum from Frostfire Mine',9,null,1,0,null,null],
  // Battlefield epic — Be selected as Combatant/Sub for Foundry Battle X time(s)
  ['Battlefield epic','Be selected as Combatant/Sub for Foundry Battle X time(s)',1,'1',0,0,'Rare','Rare Puzzle Fragment'],
  ['Battlefield epic','Be selected as Combatant/Sub for Foundry Battle X time(s)',2,'2',0,0,'Rare','Rare Puzzle Fragment'],
  ['Battlefield epic','Be selected as Combatant/Sub for Foundry Battle X time(s)',3,'4',0,0,'Rare','Rare Puzzle Fragment'],
  ['Battlefield epic','Be selected as Combatant/Sub for Foundry Battle X time(s)',4,'8',0,0,'Epic','Epic Puzzle Fragment'],
  ['Battlefield epic','Be selected as Combatant/Sub for Foundry Battle X time(s)',5,'15',0,0,'Epic','Epic Puzzle Fragment'],
  ['Battlefield epic','Be selected as Combatant/Sub for Foundry Battle X time(s)',6,null,1,0,null,null],
  // Battlefield epic — Participate in Sunfire Castle Battle X season(s)
  ['Battlefield epic','Participate in Sunfire Castle Battle X season(s)',1,'1',0,0,'Rare','Rare Puzzle Fragment'],
  ['Battlefield epic','Participate in Sunfire Castle Battle X season(s)',2,'2',0,0,'Rare','Rare Puzzle Fragment'],
  ['Battlefield epic','Participate in Sunfire Castle Battle X season(s)',3,'4',0,0,'Rare','Rare Puzzle Fragment'],
  ['Battlefield epic','Participate in Sunfire Castle Battle X season(s)',4,'8',0,0,'Epic','Epic Puzzle Fragment'],
  ['Battlefield epic','Participate in Sunfire Castle Battle X season(s)',5,'15',0,0,'Epic','Epic Puzzle Fragment'],
  ['Battlefield epic','Participate in Sunfire Castle Battle X season(s)',6,null,1,0,null,null],
  // Battlefield epic — Become President / Supreme President
  ['Battlefield epic','Become President (excl. Supreme President)',1,'1',0,1,'Mythic','Mythic Puzzle Fragment'],
  ['Battlefield epic','Become Supreme President',1,'1',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Spectacular Adventures — Spend X Fuel in the Snowbusters event
  ['Spectacular Adventures','Spend X Fuel in the Snowbusters event',1,'20,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Spectacular Adventures','Spend X Fuel in the Snowbusters event',2,'60,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Spectacular Adventures','Spend X Fuel in the Snowbusters event',3,'120,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Spectacular Adventures','Spend X Fuel in the Snowbusters event',4,'180,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Spectacular Adventures','Spend X Fuel in the Snowbusters event',5,'240,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Spectacular Adventures','Spend X Fuel in the Snowbusters event',6,'300,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Spectacular Adventures','Spend X Fuel in the Snowbusters event',7,'400,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Spectacular Adventures','Spend X Fuel in the Snowbusters event',8,null,1,0,null,null],
  // Spectacular Adventures — Get X Fishing Points
  ['Spectacular Adventures','Get X Fishing Points',1,'25,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Spectacular Adventures','Get X Fishing Points',2,'50,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Spectacular Adventures','Get X Fishing Points',3,'100,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Spectacular Adventures','Get X Fishing Points',4,'160,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Spectacular Adventures','Get X Fishing Points',5,'240,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Spectacular Adventures','Get X Fishing Points',6,'420,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Spectacular Adventures','Get X Fishing Points',7,'600,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Spectacular Adventures','Get X Fishing Points',8,'900,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Spectacular Adventures','Get X Fishing Points',9,'1,200,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Spectacular Adventures — Earn X Personal Point(s) in the Crazy Joe event
  ['Spectacular Adventures','Earn X Personal Point(s) in the Crazy Joe event',1,'500,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Spectacular Adventures','Earn X Personal Point(s) in the Crazy Joe event',2,'1,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Spectacular Adventures','Earn X Personal Point(s) in the Crazy Joe event',3,'1,800,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Spectacular Adventures','Earn X Personal Point(s) in the Crazy Joe event',4,'3,750,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Spectacular Adventures','Earn X Personal Point(s) in the Crazy Joe event',5,'7,500,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Spectacular Adventures','Earn X Personal Point(s) in the Crazy Joe event',6,'15,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Spectacular Adventures','Earn X Personal Point(s) in the Crazy Joe event',7,'30,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Spectacular Adventures','Earn X Personal Point(s) in the Crazy Joe event',8,'60,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Spectacular Adventures','Earn X Personal Point(s) in the Crazy Joe event',9,'120,000,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Spectacular Adventures — Clear Mercenary Prestige event X time(s)
  ['Spectacular Adventures','Clear Mercenary Prestige event X time(s)',1,'1',0,0,'Rare','Rare Puzzle Fragment'],
  ['Spectacular Adventures','Clear Mercenary Prestige event X time(s)',2,'3',0,0,'Rare','Rare Puzzle Fragment'],
  ['Spectacular Adventures','Clear Mercenary Prestige event X time(s)',3,'5',0,0,'Rare','Rare Puzzle Fragment'],
  ['Spectacular Adventures','Clear Mercenary Prestige event X time(s)',4,'8',0,0,'Epic','Epic Puzzle Fragment'],
  ['Spectacular Adventures','Clear Mercenary Prestige event X time(s)',5,null,1,0,null,null],
  // Spectacular Adventures — Earn X Personal Point(s) in Alliance Mobilization event
  ['Spectacular Adventures','Earn X Personal Point(s) in Alliance Mobilization event',1,'5,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Spectacular Adventures','Earn X Personal Point(s) in Alliance Mobilization event',2,'21,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Spectacular Adventures','Earn X Personal Point(s) in Alliance Mobilization event',3,'41,500',0,0,'Rare','Rare Puzzle Fragment'],
  ['Spectacular Adventures','Earn X Personal Point(s) in Alliance Mobilization event',4,'62,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Spectacular Adventures','Earn X Personal Point(s) in Alliance Mobilization event',5,'103,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Spectacular Adventures','Earn X Personal Point(s) in Alliance Mobilization event',6,'140,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Spectacular Adventures','Earn X Personal Point(s) in Alliance Mobilization event',7,'200,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Spectacular Adventures','Earn X Personal Point(s) in Alliance Mobilization event',8,'275,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Spectacular Adventures','Earn X Personal Point(s) in Alliance Mobilization event',9,'360,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Spectacular Adventures — Win X Alliance Championships
  ['Spectacular Adventures','Win X Alliance Championships',1,'2',0,0,'Rare','Rare Puzzle Fragment'],
  ['Spectacular Adventures','Win X Alliance Championships',2,'8',0,0,'Rare','Rare Puzzle Fragment'],
  ['Spectacular Adventures','Win X Alliance Championships',3,'16',0,0,'Rare','Rare Puzzle Fragment'],
  ['Spectacular Adventures','Win X Alliance Championships',4,'25',0,0,'Epic','Epic Puzzle Fragment'],
  ['Spectacular Adventures','Win X Alliance Championships',5,null,1,0,null,null],
  // Divine Weapons — Reach Lv. X for any Hero Gear piece
  ['Divine Weapons','Reach Lv. X for any Hero Gear piece',1,'10',0,0,'Rare','Rare Puzzle Fragment'],
  ['Divine Weapons','Reach Lv. X for any Hero Gear piece',2,'20',0,0,'Rare','Rare Puzzle Fragment'],
  ['Divine Weapons','Reach Lv. X for any Hero Gear piece',3,'30',0,0,'Rare','Rare Puzzle Fragment'],
  ['Divine Weapons','Reach Lv. X for any Hero Gear piece',4,'40',0,0,'Epic','Epic Puzzle Fragment'],
  ['Divine Weapons','Reach Lv. X for any Hero Gear piece',5,'50',0,0,'Epic','Epic Puzzle Fragment'],
  ['Divine Weapons','Reach Lv. X for any Hero Gear piece',6,'60',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Divine Weapons','Reach Lv. X for any Hero Gear piece',7,'70',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Divine Weapons','Reach Lv. X for any Hero Gear piece',8,'85',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Divine Weapons','Reach Lv. X for any Hero Gear piece',9,'100',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Divine Weapons — Own X piece(s) of Mythic Hero Gear
  ['Divine Weapons','Own X piece(s) of Mythic Hero Gear',1,'1',0,0,'Rare','Rare Puzzle Fragment'],
  ['Divine Weapons','Own X piece(s) of Mythic Hero Gear',2,'2',0,0,'Rare','Rare Puzzle Fragment'],
  ['Divine Weapons','Own X piece(s) of Mythic Hero Gear',3,'3',0,0,'Rare','Rare Puzzle Fragment'],
  ['Divine Weapons','Own X piece(s) of Mythic Hero Gear',4,'4',0,0,'Epic','Epic Puzzle Fragment'],
  ['Divine Weapons','Own X piece(s) of Mythic Hero Gear',5,'6',0,0,'Epic','Epic Puzzle Fragment'],
  ['Divine Weapons','Own X piece(s) of Mythic Hero Gear',6,'8',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Divine Weapons','Own X piece(s) of Mythic Hero Gear',7,'12',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Divine Weapons','Own X piece(s) of Mythic Hero Gear',8,'16',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Divine Weapons','Own X piece(s) of Mythic Hero Gear',9,'20',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Divine Weapons — Highest Hero Gear Mastery Level reaches Lv. X
  ['Divine Weapons','Highest Hero Gear Mastery Level reaches Lv. X',1,'1',0,0,'Rare','Rare Puzzle Fragment'],
  ['Divine Weapons','Highest Hero Gear Mastery Level reaches Lv. X',2,'2',0,0,'Rare','Rare Puzzle Fragment'],
  ['Divine Weapons','Highest Hero Gear Mastery Level reaches Lv. X',3,'3',0,0,'Rare','Rare Puzzle Fragment'],
  ['Divine Weapons','Highest Hero Gear Mastery Level reaches Lv. X',4,'4',0,0,'Epic','Epic Puzzle Fragment'],
  ['Divine Weapons','Highest Hero Gear Mastery Level reaches Lv. X',5,'6',0,0,'Epic','Epic Puzzle Fragment'],
  ['Divine Weapons','Highest Hero Gear Mastery Level reaches Lv. X',6,'8',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Divine Weapons','Highest Hero Gear Mastery Level reaches Lv. X',7,'12',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Divine Weapons','Highest Hero Gear Mastery Level reaches Lv. X',8,'16',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Divine Weapons','Highest Hero Gear Mastery Level reaches Lv. X',9,'20',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Divine Weapons — Own 12 piece(s) of Mastery Lv. X gear
  ['Divine Weapons','Own 12 piece(s) of Mastery Lv. X gear',1,'1',0,0,'Rare','Rare Puzzle Fragment'],
  ['Divine Weapons','Own 12 piece(s) of Mastery Lv. X gear',2,'2',0,0,'Rare','Rare Puzzle Fragment'],
  ['Divine Weapons','Own 12 piece(s) of Mastery Lv. X gear',3,'3',0,0,'Rare','Rare Puzzle Fragment'],
  ['Divine Weapons','Own 12 piece(s) of Mastery Lv. X gear',4,'4',0,0,'Epic','Epic Puzzle Fragment'],
  ['Divine Weapons','Own 12 piece(s) of Mastery Lv. X gear',5,'6',0,0,'Epic','Epic Puzzle Fragment'],
  ['Divine Weapons','Own 12 piece(s) of Mastery Lv. X gear',6,'8',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Divine Weapons','Own 12 piece(s) of Mastery Lv. X gear',7,'11',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Divine Weapons','Own 12 piece(s) of Mastery Lv. X gear',8,'15',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Divine Weapons','Own 12 piece(s) of Mastery Lv. X gear',9,'20',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Divine Weapons — Chief Gear Total Power reaches X
  ['Divine Weapons','Chief Gear Total Power reaches X',1,'1,836,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Divine Weapons','Chief Gear Total Power reaches X',2,'3,060,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Divine Weapons','Chief Gear Total Power reaches X',3,'4,284,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Divine Weapons','Chief Gear Total Power reaches X',4,'5,312,160',0,0,'Epic','Epic Puzzle Fragment'],
  ['Divine Weapons','Chief Gear Total Power reaches X',5,'6,560,640',0,0,'Epic','Epic Puzzle Fragment'],
  ['Divine Weapons','Chief Gear Total Power reaches X',6,'7,809,120',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Divine Weapons','Chief Gear Total Power reaches X',7,'8,910,720',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Divine Weapons','Chief Gear Total Power reaches X',8,'10,746,720',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Divine Weapons','Chief Gear Total Power reaches X',9,'12,240,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Divine Weapons — Chief Charm Total Power reaches X
  ['Divine Weapons','Chief Charm Total Power reaches X',1,'3,702,600',0,0,'Rare','Rare Puzzle Fragment'],
  ['Divine Weapons','Chief Charm Total Power reaches X',2,'5,184,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Divine Weapons','Chief Charm Total Power reaches X',3,'6,660,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Divine Weapons','Chief Charm Total Power reaches X',4,'8,136,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Divine Weapons','Chief Charm Total Power reaches X',5,'10,368,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Divine Weapons','Chief Charm Total Power reaches X',6,'12,600,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Divine Weapons','Chief Charm Total Power reaches X',7,'14,832,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Divine Weapons','Chief Charm Total Power reaches X',8,'17,064,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Divine Weapons','Chief Charm Total Power reaches X',9,'19,296,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // The Labyrinth — Clear stage X-10 of Land of the Brave
  ['The Labyrinth','Clear stage X-10 of Land of the Brave',1,'6',0,0,'Rare','Rare Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Land of the Brave',2,'12',0,0,'Rare','Rare Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Land of the Brave',3,'18',0,0,'Rare','Rare Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Land of the Brave',4,'24',0,0,'Epic','Epic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Land of the Brave',5,'31',0,0,'Epic','Epic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Land of the Brave',6,'38',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Land of the Brave',7,'45',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Land of the Brave',8,'52',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Land of the Brave',9,'60',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Land of the Brave',10,null,1,0,null,null],
  // The Labyrinth — Clear stage X-10 of Earthlab
  ['The Labyrinth','Clear stage X-10 of Earthlab',1,'2',0,0,'Rare','Rare Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Earthlab',2,'4',0,0,'Rare','Rare Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Earthlab',3,'6',0,0,'Rare','Rare Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Earthlab',4,'8',0,0,'Epic','Epic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Earthlab',5,'10',0,0,'Epic','Epic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Earthlab',6,'12',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Earthlab',7,'14',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Earthlab',8,'17',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Earthlab',9,'20',0,1,'Mythic','Mythic Puzzle Fragment'],
  // The Labyrinth — Clear stage X-10 of Dark Forge
  ['The Labyrinth','Clear stage X-10 of Dark Forge',1,'2',0,0,'Rare','Rare Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Dark Forge',2,'4',0,0,'Rare','Rare Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Dark Forge',3,'6',0,0,'Rare','Rare Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Dark Forge',4,'9',0,0,'Epic','Epic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Dark Forge',5,'12',0,0,'Epic','Epic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Dark Forge',6,'15',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Dark Forge',7,'18',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Dark Forge',8,'21',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Dark Forge',9,'25',0,1,'Mythic','Mythic Puzzle Fragment'],
  // The Labyrinth — Clear stage X-10 of Glowstone Mine
  ['The Labyrinth','Clear stage X-10 of Glowstone Mine',1,'2',0,0,'Rare','Rare Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Glowstone Mine',2,'4',0,0,'Rare','Rare Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Glowstone Mine',3,'7',0,0,'Rare','Rare Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Glowstone Mine',4,'10',0,0,'Epic','Epic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Glowstone Mine',5,'13',0,0,'Epic','Epic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Glowstone Mine',6,'16',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Glowstone Mine',7,'19',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Glowstone Mine',8,'22',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Glowstone Mine',9,'25',0,1,'Mythic','Mythic Puzzle Fragment'],
  // The Labyrinth — Clear stage X-10 of Cave of Monsters
  ['The Labyrinth','Clear stage X-10 of Cave of Monsters',1,'2',0,0,'Rare','Rare Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Cave of Monsters',2,'4',0,0,'Rare','Rare Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Cave of Monsters',3,'6',0,0,'Rare','Rare Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Cave of Monsters',4,'8',0,0,'Epic','Epic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Cave of Monsters',5,'10',0,0,'Epic','Epic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Cave of Monsters',6,'12',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Cave of Monsters',7,'14',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Cave of Monsters',8,'17',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Cave of Monsters',9,'20',0,1,'Mythic','Mythic Puzzle Fragment'],
  // The Labyrinth — Clear stage X-10 of Gaia Heart
  ['The Labyrinth','Clear stage X-10 of Gaia Heart',1,'7',0,0,'Rare','Rare Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Gaia Heart',2,'14',0,0,'Rare','Rare Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Gaia Heart',3,'21',0,0,'Rare','Rare Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Gaia Heart',4,'28',0,0,'Epic','Epic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Gaia Heart',5,'35',0,0,'Epic','Epic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Gaia Heart',6,'42',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Gaia Heart',7,'49',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Gaia Heart',8,'57',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Gaia Heart',9,'65',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['The Labyrinth','Clear stage X-10 of Gaia Heart',10,null,1,0,null,null],
  // Nature's Strength — Tame X pet(s)
  ["Nature's Strength",'Tame X pet(s)',1,'1',0,0,'Rare','Rare Puzzle Fragment'],
  ["Nature's Strength",'Tame X pet(s)',2,'2',0,0,'Rare','Rare Puzzle Fragment'],
  ["Nature's Strength",'Tame X pet(s)',3,'3',0,0,'Rare','Rare Puzzle Fragment'],
  ["Nature's Strength",'Tame X pet(s)',4,'5',0,0,'Epic','Epic Puzzle Fragment'],
  ["Nature's Strength",'Tame X pet(s)',5,'7',0,0,'Epic','Epic Puzzle Fragment'],
  ["Nature's Strength",'Tame X pet(s)',6,'9',0,0,'Mythic','Mythic Puzzle Fragment'],
  ["Nature's Strength",'Tame X pet(s)',7,'11',0,0,'Mythic','Mythic Puzzle Fragment'],
  ["Nature's Strength",'Tame X pet(s)',8,'13',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Nature's Strength — Upgrade X pet(s) to Lv. Y
  ["Nature's Strength",'Upgrade X pet(s) to Lv. Y',1,'2/lv10',0,0,'Rare','Rare Puzzle Fragment'],
  ["Nature's Strength",'Upgrade X pet(s) to Lv. Y',2,'2/lv30',0,0,'Rare','Rare Puzzle Fragment'],
  ["Nature's Strength",'Upgrade X pet(s) to Lv. Y',3,'4/lv30',0,0,'Epic','Epic Puzzle Fragment'],
  ["Nature's Strength",'Upgrade X pet(s) to Lv. Y',4,'4/lv50',0,0,'Epic','Epic Puzzle Fragment'],
  ["Nature's Strength",'Upgrade X pet(s) to Lv. Y',5,'6/lv50',0,0,'Epic','Epic Puzzle Fragment'],
  ["Nature's Strength",'Upgrade X pet(s) to Lv. Y',6,'6/lv60',0,0,'Mythic','Mythic Puzzle Fragment'],
  ["Nature's Strength",'Upgrade X pet(s) to Lv. Y',7,'8/lv60',0,0,'Mythic','Mythic Puzzle Fragment'],
  ["Nature's Strength",'Upgrade X pet(s) to Lv. Y',8,'8/lv70',0,0,'Mythic','Mythic Puzzle Fragment'],
  ["Nature's Strength",'Upgrade X pet(s) to Lv. Y',9,'8/lv80',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Nature's Strength — Reach X Pet Power
  ["Nature's Strength",'Reach X Pet Power',1,'80,000',0,0,'Rare','Rare Puzzle Fragment'],
  ["Nature's Strength",'Reach X Pet Power',2,'160,000',0,0,'Rare','Rare Puzzle Fragment'],
  ["Nature's Strength",'Reach X Pet Power',3,'320,000',0,0,'Epic','Epic Puzzle Fragment'],
  ["Nature's Strength",'Reach X Pet Power',4,'640,000',0,0,'Epic','Epic Puzzle Fragment'],
  ["Nature's Strength",'Reach X Pet Power',5,'1,280,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ["Nature's Strength",'Reach X Pet Power',6,'2,560,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ["Nature's Strength",'Reach X Pet Power',7,'5,120,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ["Nature's Strength",'Reach X Pet Power',8,'9,600,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ["Nature's Strength",'Reach X Pet Power',9,'16,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ["Nature's Strength",'Reach X Pet Power',10,'38,000,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Nature's Strength — Dispatch Pets to hunt for treasure X times
  ["Nature's Strength",'Dispatch Pets to hunt for treasure X times',1,'100',0,0,'Rare','Rare Puzzle Fragment'],
  ["Nature's Strength",'Dispatch Pets to hunt for treasure X times',2,'200',0,0,'Rare','Rare Puzzle Fragment'],
  ["Nature's Strength",'Dispatch Pets to hunt for treasure X times',3,'400',0,0,'Rare','Rare Puzzle Fragment'],
  ["Nature's Strength",'Dispatch Pets to hunt for treasure X times',4,null,1,0,null,null],
  // Nature's Strength — Use pet skills X time(s)
  ["Nature's Strength",'Use pet skills X time(s)',1,'200',0,0,'Rare','Rare Puzzle Fragment'],
  ["Nature's Strength",'Use pet skills X time(s)',2,'400',0,0,'Rare','Rare Puzzle Fragment'],
  ["Nature's Strength",'Use pet skills X time(s)',3,'800',0,0,'Rare','Rare Puzzle Fragment'],
  ["Nature's Strength",'Use pet skills X time(s)',4,'1,200',0,0,'Epic','Epic Puzzle Fragment'],
  ["Nature's Strength",'Use pet skills X time(s)',5,null,1,0,null,null],
  // Crystalline Mysteries — Reach Furnace Lv. Fire Crystal X
  ['Crystalline Mysteries','Reach Furnace Lv. Fire Crystal X',1,'1',0,0,'Rare','Rare Puzzle Fragment'],
  ['Crystalline Mysteries','Reach Furnace Lv. Fire Crystal X',2,'2',0,0,'Epic','Epic Puzzle Fragment'],
  ['Crystalline Mysteries','Reach Furnace Lv. Fire Crystal X',3,'3',0,0,'Epic','Epic Puzzle Fragment'],
  ['Crystalline Mysteries','Reach Furnace Lv. Fire Crystal X',4,'4',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Crystalline Mysteries','Reach Furnace Lv. Fire Crystal X',5,'5',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Crystalline Mysteries — Reach Infantry Camp Lv. Fire Crystal X
  ['Crystalline Mysteries','Reach Infantry Camp Lv. Fire Crystal X',1,'1',0,0,'Rare','Rare Puzzle Fragment'],
  ['Crystalline Mysteries','Reach Infantry Camp Lv. Fire Crystal X',2,'2',0,0,'Epic','Epic Puzzle Fragment'],
  ['Crystalline Mysteries','Reach Infantry Camp Lv. Fire Crystal X',3,'3',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Crystalline Mysteries','Reach Infantry Camp Lv. Fire Crystal X',4,'4',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Crystalline Mysteries','Reach Infantry Camp Lv. Fire Crystal X',5,'5',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Crystalline Mysteries — Reach Lancer Camp Lv. Fire Crystal X
  ['Crystalline Mysteries','Reach Lancer Camp Lv. Fire Crystal X',1,'1',0,0,'Rare','Rare Puzzle Fragment'],
  ['Crystalline Mysteries','Reach Lancer Camp Lv. Fire Crystal X',2,'2',0,0,'Epic','Epic Puzzle Fragment'],
  ['Crystalline Mysteries','Reach Lancer Camp Lv. Fire Crystal X',3,'3',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Crystalline Mysteries','Reach Lancer Camp Lv. Fire Crystal X',4,'4',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Crystalline Mysteries','Reach Lancer Camp Lv. Fire Crystal X',5,'5',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Crystalline Mysteries — Reach Marksman Camp Lv. Fire Crystal X
  ['Crystalline Mysteries','Reach Marksman Camp Lv. Fire Crystal X',1,'1',0,0,'Rare','Rare Puzzle Fragment'],
  ['Crystalline Mysteries','Reach Marksman Camp Lv. Fire Crystal X',2,'2',0,0,'Epic','Epic Puzzle Fragment'],
  ['Crystalline Mysteries','Reach Marksman Camp Lv. Fire Crystal X',3,'3',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Crystalline Mysteries','Reach Marksman Camp Lv. Fire Crystal X',4,'4',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Crystalline Mysteries','Reach Marksman Camp Lv. Fire Crystal X',5,'5',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Crystalline Mysteries — Use X Crystallite Core(s) in [Flame and Fangs]
  ['Crystalline Mysteries','Use X Crystallite Core(s) in [Flame and Fangs]',1,'150',0,0,'Rare','Rare Puzzle Fragment'],
  ['Crystalline Mysteries','Use X Crystallite Core(s) in [Flame and Fangs]',2,'300',0,0,'Rare','Rare Puzzle Fragment'],
  ['Crystalline Mysteries','Use X Crystallite Core(s) in [Flame and Fangs]',3,'500',0,0,'Rare','Rare Puzzle Fragment'],
  ['Crystalline Mysteries','Use X Crystallite Core(s) in [Flame and Fangs]',4,'800',0,0,'Rare','Rare Puzzle Fragment'],
  ['Crystalline Mysteries','Use X Crystallite Core(s) in [Flame and Fangs]',5,'1,200',0,0,'Epic','Epic Puzzle Fragment'],
  ['Crystalline Mysteries','Use X Crystallite Core(s) in [Flame and Fangs]',6,null,1,0,null,null],
  // Crystalline Mysteries — Perform X standard refinement(s) in Crystal Lab
  ['Crystalline Mysteries','Perform X standard refinement(s) in Crystal Lab',1,'70',0,0,'Rare','Rare Puzzle Fragment'],
  ['Crystalline Mysteries','Perform X standard refinement(s) in Crystal Lab',2,'150',0,0,'Rare','Rare Puzzle Fragment'],
  ['Crystalline Mysteries','Perform X standard refinement(s) in Crystal Lab',3,'250',0,0,'Rare','Rare Puzzle Fragment'],
  ['Crystalline Mysteries','Perform X standard refinement(s) in Crystal Lab',4,'400',0,0,'Rare','Rare Puzzle Fragment'],
  ['Crystalline Mysteries','Perform X standard refinement(s) in Crystal Lab',5,'600',0,0,'Epic','Epic Puzzle Fragment'],
  ['Crystalline Mysteries','Perform X standard refinement(s) in Crystal Lab',6,'900',0,0,'Epic','Epic Puzzle Fragment'],
  ['Crystalline Mysteries','Perform X standard refinement(s) in Crystal Lab',7,null,1,0,null,null],
  // Ballad of Wind and Cold — Obtain X Medal(s) of Honor in [King of Icefield]
  ['Ballad of Wind and Cold','Obtain X Medal(s) of Honor in [King of Icefield]',1,'25',0,0,'Rare','Rare Puzzle Fragment'],
  ['Ballad of Wind and Cold','Obtain X Medal(s) of Honor in [King of Icefield]',2,'60',0,0,'Rare','Rare Puzzle Fragment'],
  ['Ballad of Wind and Cold','Obtain X Medal(s) of Honor in [King of Icefield]',3,null,1,0,null,null],
  // Ballad of Wind and Cold — Obtain X State Medal(s) in [State of Power]
  ['Ballad of Wind and Cold','Obtain X State Medal(s) in [State of Power]',1,'10',0,0,'Rare','Rare Puzzle Fragment'],
  ['Ballad of Wind and Cold','Obtain X State Medal(s) in [State of Power]',2,'20',0,0,'Rare','Rare Puzzle Fragment'],
  ['Ballad of Wind and Cold','Obtain X State Medal(s) in [State of Power]',3,null,1,0,null,null],
  // Ballad of Wind and Cold — Earn X points in Cross-State Battle Phase of [State of Power]
  ['Ballad of Wind and Cold','Earn X points in Cross-State Battle Phase of [State of Power]',1,'20,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Ballad of Wind and Cold','Earn X points in Cross-State Battle Phase of [State of Power]',2,'50,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Ballad of Wind and Cold','Earn X points in Cross-State Battle Phase of [State of Power]',3,'100,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Ballad of Wind and Cold','Earn X points in Cross-State Battle Phase of [State of Power]',4,'200,000,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Ballad of Wind and Cold','Earn X points in Cross-State Battle Phase of [State of Power]',5,'400,000,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Ballad of Wind and Cold','Earn X points in Cross-State Battle Phase of [State of Power]',6,'700,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Ballad of Wind and Cold','Earn X points in Cross-State Battle Phase of [State of Power]',7,'1,000,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Ballad of Wind and Cold','Earn X points in Cross-State Battle Phase of [State of Power]',8,'1,300,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Ballad of Wind and Cold','Earn X points in Cross-State Battle Phase of [State of Power]',9,'1,600,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Ballad of Wind and Cold','Earn X points in Cross-State Battle Phase of [State of Power]',10,'2,000,000,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Ballad of Wind and Cold — Escort X trucks of any grade
  ['Ballad of Wind and Cold','Escort X trucks of any grade',1,'20',0,0,'Rare','Rare Puzzle Fragment'],
  ['Ballad of Wind and Cold','Escort X trucks of any grade',2,'50',0,0,'Rare','Rare Puzzle Fragment'],
  ['Ballad of Wind and Cold','Escort X trucks of any grade',3,'100',0,0,'Rare','Rare Puzzle Fragment'],
  ['Ballad of Wind and Cold','Escort X trucks of any grade',4,null,1,0,null,null],
  // Ballad of Wind and Cold — Claim daily chests X time(s) in [Alliance Showdown]
  ['Ballad of Wind and Cold','Claim daily chests X time(s) in [Alliance Showdown]',1,'25',0,0,'Rare','Rare Puzzle Fragment'],
  ['Ballad of Wind and Cold','Claim daily chests X time(s) in [Alliance Showdown]',2,'50',0,0,'Rare','Rare Puzzle Fragment'],
  ['Ballad of Wind and Cold','Claim daily chests X time(s) in [Alliance Showdown]',3,'100',0,0,'Rare','Rare Puzzle Fragment'],
  ['Ballad of Wind and Cold','Claim daily chests X time(s) in [Alliance Showdown]',4,'200',0,0,'Epic','Epic Puzzle Fragment'],
  ['Ballad of Wind and Cold','Claim daily chests X time(s) in [Alliance Showdown]',5,null,1,0,null,null],
  // Infernal Power — Reach War Academy Lv. Fire Crystal X
  ['Infernal Power','Reach War Academy Lv. Fire Crystal X',1,'1',0,0,'Rare','Rare Puzzle Fragment'],
  ['Infernal Power','Reach War Academy Lv. Fire Crystal X',2,'2',0,0,'Rare','Rare Puzzle Fragment'],
  ['Infernal Power','Reach War Academy Lv. Fire Crystal X',3,'3',0,0,'Epic','Epic Puzzle Fragment'],
  ['Infernal Power','Reach War Academy Lv. Fire Crystal X',4,'4',0,0,'Epic','Epic Puzzle Fragment'],
  ['Infernal Power','Reach War Academy Lv. Fire Crystal X',5,'5',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Infernal Power — Reach X Fire Crystal Tech Power
  ['Infernal Power','Reach X Fire Crystal Tech Power',1,'300,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Infernal Power','Reach X Fire Crystal Tech Power',2,'600,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Infernal Power','Reach X Fire Crystal Tech Power',3,'1,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Infernal Power','Reach X Fire Crystal Tech Power',4,'1,500,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Infernal Power','Reach X Fire Crystal Tech Power',5,'2,500,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Infernal Power','Reach X Fire Crystal Tech Power',6,'4,000,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Infernal Power','Reach X Fire Crystal Tech Power',7,'6,000,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Infernal Power','Reach X Fire Crystal Tech Power',8,'10,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Infernal Power','Reach X Fire Crystal Tech Power',9,'15,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Infernal Power','Reach X Fire Crystal Tech Power',10,'20,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Infernal Power','Reach X Fire Crystal Tech Power',11,'25,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Infernal Power','Reach X Fire Crystal Tech Power',12,'30,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Infernal Power','Reach X Fire Crystal Tech Power',13,'38,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Infernal Power','Reach X Fire Crystal Tech Power',14,'46,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Infernal Power','Reach X Fire Crystal Tech Power',15,'54,000,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Infernal Power — Unlock Helios troops
  ['Infernal Power','Unlock Helios Infantry',1,'1',0,1,'Mythic','Mythic Puzzle Fragment'],
  ['Infernal Power','Unlock Helios Lancers',1,'1',0,1,'Mythic','Mythic Puzzle Fragment'],
  ['Infernal Power','Unlock Helios Marksmen',1,'1',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Infernal Power — Train X Lv. 11 Troop(s)
  ['Infernal Power','Train X Lv. 11 Troop(s)',1,'50,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Infernal Power','Train X Lv. 11 Troop(s)',2,'100,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Infernal Power','Train X Lv. 11 Troop(s)',3,'200,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Infernal Power','Train X Lv. 11 Troop(s)',4,'300,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Infernal Power','Train X Lv. 11 Troop(s)',5,'500,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Infernal Power','Train X Lv. 11 Troop(s)',6,'700,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Infernal Power','Train X Lv. 11 Troop(s)',7,'900,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Infernal Power','Train X Lv. 11 Troop(s)',8,'1,100,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Infernal Power','Train X Lv. 11 Troop(s)',9,'1,300,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Infernal Power','Train X Lv. 11 Troop(s)',10,'1,500,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Infernal Power','Train X Lv. 11 Troop(s)',11,'1,700,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Infernal Power','Train X Lv. 11 Troop(s)',12,'1,900,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Infernal Power','Train X Lv. 11 Troop(s)',13,'2,100,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Infernal Power','Train X Lv. 11 Troop(s)',14,'2,300,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Infernal Power','Train X Lv. 11 Troop(s)',15,'2,500,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Infernal Power — Complete X commission(s) in [Fire Crystal Lore]
  ['Infernal Power','Complete X commission(s) in [Fire Crystal Lore]',1,'18',0,0,'Rare','Rare Puzzle Fragment'],
  ['Infernal Power','Complete X commission(s) in [Fire Crystal Lore]',2,'40',0,0,'Rare','Rare Puzzle Fragment'],
  ['Infernal Power','Complete X commission(s) in [Fire Crystal Lore]',3,'80',0,0,'Rare','Rare Puzzle Fragment'],
  ['Infernal Power','Complete X commission(s) in [Fire Crystal Lore]',4,'140',0,0,'Epic','Epic Puzzle Fragment'],
  ['Infernal Power','Complete X commission(s) in [Fire Crystal Lore]',5,null,1,0,null,null],
  // Prerogative of the Flame — Reach Infantry Camp Lv. Fire Crystal X
  ['Prerogative of the Flame','Reach Infantry Camp Lv. Fire Crystal X',1,'6',0,0,'Rare','Rare Puzzle Fragment'],
  ['Prerogative of the Flame','Reach Infantry Camp Lv. Fire Crystal X',2,'7',0,0,'Epic','Epic Puzzle Fragment'],
  ['Prerogative of the Flame','Reach Infantry Camp Lv. Fire Crystal X',3,'8',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Prerogative of the Flame','Reach Infantry Camp Lv. Fire Crystal X',4,'9',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Prerogative of the Flame','Reach Infantry Camp Lv. Fire Crystal X',5,'10',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Prerogative of the Flame — Reach Marksman Camp Lv. Fire Crystal X
  ['Prerogative of the Flame','Reach Marksman Camp Lv. Fire Crystal X',1,'6',0,0,'Rare','Rare Puzzle Fragment'],
  ['Prerogative of the Flame','Reach Marksman Camp Lv. Fire Crystal X',2,'7',0,0,'Epic','Epic Puzzle Fragment'],
  ['Prerogative of the Flame','Reach Marksman Camp Lv. Fire Crystal X',3,'8',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Prerogative of the Flame','Reach Marksman Camp Lv. Fire Crystal X',4,'9',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Prerogative of the Flame','Reach Marksman Camp Lv. Fire Crystal X',5,'10',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Prerogative of the Flame — Reach Lancer Camp Lv. Fire Crystal X
  ['Prerogative of the Flame','Reach Lancer Camp Lv. Fire Crystal X',1,'6',0,0,'Rare','Rare Puzzle Fragment'],
  ['Prerogative of the Flame','Reach Lancer Camp Lv. Fire Crystal X',2,'7',0,0,'Epic','Epic Puzzle Fragment'],
  ['Prerogative of the Flame','Reach Lancer Camp Lv. Fire Crystal X',3,'8',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Prerogative of the Flame','Reach Lancer Camp Lv. Fire Crystal X',4,'9',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Prerogative of the Flame','Reach Lancer Camp Lv. Fire Crystal X',5,'10',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Prerogative of the Flame — Reach Furnace Lv. Fire Crystal X
  ['Prerogative of the Flame','Reach Furnace Lv. Fire Crystal X',1,'6',0,0,'Rare','Rare Puzzle Fragment'],
  ['Prerogative of the Flame','Reach Furnace Lv. Fire Crystal X',2,'7',0,0,'Epic','Epic Puzzle Fragment'],
  ['Prerogative of the Flame','Reach Furnace Lv. Fire Crystal X',3,'8',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Prerogative of the Flame','Reach Furnace Lv. Fire Crystal X',4,'9',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Prerogative of the Flame','Reach Furnace Lv. Fire Crystal X',5,'10',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Prerogative of the Flame — Perform X super refinement(s) in Crystal Lab
  ['Prerogative of the Flame','Perform X super refinement(s) in Crystal Lab',1,'20',0,0,'Rare','Rare Puzzle Fragment'],
  ['Prerogative of the Flame','Perform X super refinement(s) in Crystal Lab',2,'50',0,0,'Rare','Rare Puzzle Fragment'],
  ['Prerogative of the Flame','Perform X super refinement(s) in Crystal Lab',3,'100',0,0,'Rare','Rare Puzzle Fragment'],
  ['Prerogative of the Flame','Perform X super refinement(s) in Crystal Lab',4,'150',0,0,'Epic','Epic Puzzle Fragment'],
  ['Prerogative of the Flame','Perform X super refinement(s) in Crystal Lab',5,'200',0,0,'Epic','Epic Puzzle Fragment'],
  ['Prerogative of the Flame','Perform X super refinement(s) in Crystal Lab',6,'280',0,0,'Epic','Epic Puzzle Fragment'],
  ['Prerogative of the Flame','Perform X super refinement(s) in Crystal Lab',7,'360',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Prerogative of the Flame','Perform X super refinement(s) in Crystal Lab',8,'440',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Prerogative of the Flame','Perform X super refinement(s) in Crystal Lab',9,'520',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Prerogative of the Flame','Perform X super refinement(s) in Crystal Lab',10,'600',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Prerogative of the Flame','Perform X super refinement(s) in Crystal Lab',11,'680',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Prerogative of the Flame','Perform X super refinement(s) in Crystal Lab',12,'760',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Prerogative of the Flame','Perform X super refinement(s) in Crystal Lab',13,'840',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Prerogative of the Flame','Perform X super refinement(s) in Crystal Lab',14,'1,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Frostdragon Empire — Become the Frostdragon Tyrant
  ['Frostdragon Empire','Become the Frostdragon Tyrant',1,'1',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Frostdragon Empire — Place X Tyrant Prediction(s)
  ['Frostdragon Empire','Place X Tyrant Prediction(s)',1,'5',0,0,'Rare','Rare Puzzle Fragment'],
  ['Frostdragon Empire','Place X Tyrant Prediction(s)',2,null,1,0,null,null],
  // Frostdragon Empire — Complete X mission(s) in Frostwind Journey
  ['Frostdragon Empire','Complete X mission(s) in Frostwind Journey',1,'30',0,0,'Rare','Rare Puzzle Fragment'],
  ['Frostdragon Empire','Complete X mission(s) in Frostwind Journey',2,'60',0,0,'Rare','Rare Puzzle Fragment'],
  ['Frostdragon Empire','Complete X mission(s) in Frostwind Journey',3,'90',0,0,'Rare','Rare Puzzle Fragment'],
  ['Frostdragon Empire','Complete X mission(s) in Frostwind Journey',4,null,1,0,null,null],
  // Frostdragon Empire — Gather X Dragonite
  ['Frostdragon Empire','Gather X Dragonite',1,'7,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Frostdragon Empire','Gather X Dragonite',2,'15,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Frostdragon Empire','Gather X Dragonite',3,'23,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Frostdragon Empire','Gather X Dragonite',4,'31,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Frostdragon Empire','Gather X Dragonite',5,'39,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Frostdragon Empire','Gather X Dragonite',6,'47,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Frostdragon Empire','Gather X Dragonite',7,'55,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Frostdragon Empire','Gather X Dragonite',8,'64,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Frostdragon Empire','Gather X Dragonite',9,'74,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Frostdragon Empire','Gather X Dragonite',10,'84,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Frostdragon Empire — Defeat X Frostdragon Escort(s)
  ['Frostdragon Empire','Defeat X Frostdragon Escort(s)',1,'10',0,0,'Rare','Rare Puzzle Fragment'],
  ['Frostdragon Empire','Defeat X Frostdragon Escort(s)',2,'20',0,0,'Rare','Rare Puzzle Fragment'],
  ['Frostdragon Empire','Defeat X Frostdragon Escort(s)',3,'30',0,0,'Rare','Rare Puzzle Fragment'],
  ['Frostdragon Empire','Defeat X Frostdragon Escort(s)',4,'40',0,0,'Epic','Epic Puzzle Fragment'],
  ['Frostdragon Empire','Defeat X Frostdragon Escort(s)',5,'50',0,0,'Epic','Epic Puzzle Fragment'],
  ['Frostdragon Empire','Defeat X Frostdragon Escort(s)',6,'60',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Frostdragon Empire','Defeat X Frostdragon Escort(s)',7,'70',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Frostdragon Empire','Defeat X Frostdragon Escort(s)',8,'80',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Frostdragon Empire','Defeat X Frostdragon Escort(s)',9,'100',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Frostdragon Empire','Defeat X Frostdragon Escort(s)',10,'120',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Frostdragon Empire — Earn X Battlefield Personal Points
  ['Frostdragon Empire','Earn X Battlefield Personal Points',1,'20,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Frostdragon Empire','Earn X Battlefield Personal Points',2,'40,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Frostdragon Empire','Earn X Battlefield Personal Points',3,'60,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Frostdragon Empire','Earn X Battlefield Personal Points',4,'80,000,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Frostdragon Empire','Earn X Battlefield Personal Points',5,'100,000,000',0,0,'Epic','Epic Puzzle Fragment'],
  ['Frostdragon Empire','Earn X Battlefield Personal Points',6,'120,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Frostdragon Empire','Earn X Battlefield Personal Points',7,'140,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Frostdragon Empire','Earn X Battlefield Personal Points',8,'160,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Frostdragon Empire','Earn X Battlefield Personal Points',9,'180,000,000',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Frostdragon Empire','Earn X Battlefield Personal Points',10,'200,000,000',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Kings of Combat — Achieve rank X or higher in [Tundra Arms League]
  ['Kings of Combat','Achieve rank X or higher in [Tundra Arms League]',1,'4',0,0,'Epic','Epic Puzzle Fragment'],
  ['Kings of Combat','Achieve rank X or higher in [Tundra Arms League]',2,'3',0,0,'Epic','Epic Puzzle Fragment'],
  ['Kings of Combat','Achieve rank X or higher in [Tundra Arms League]',3,'2',0,0,'Mythic','Mythic Puzzle Fragment'],
  ['Kings of Combat','Achieve rank X or higher in [Tundra Arms League]',4,'1',0,1,'Mythic','Mythic Puzzle Fragment'],
  // Kings of Combat — Use X Match Stake(s) in a Match Prediction
  ['Kings of Combat','Use X Match Stake(s) in a Match Prediction',1,'25,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Kings of Combat','Use X Match Stake(s) in a Match Prediction',2,null,1,0,null,null],
  // Kings of Combat — Use X Champion Stake(s) in a Champion Prediction
  ['Kings of Combat','Use X Champion Stake(s) in a Champion Prediction',1,'250',0,0,'Rare','Rare Puzzle Fragment'],
  ['Kings of Combat','Use X Champion Stake(s) in a Champion Prediction',2,null,1,0,null,null],
  // Kings of Combat — Be selected as Combatant/Sub for Tundra Arms League X time(s)
  ['Kings of Combat','Be selected as Combatant/Sub for Tundra Arms League X time(s)',1,'3',0,0,'Rare','Rare Puzzle Fragment'],
  ['Kings of Combat','Be selected as Combatant/Sub for Tundra Arms League X time(s)',2,null,1,0,null,null],
  // Kings of Combat — Earn X Personal Arsenal Points in [Tundra Arms League]
  ['Kings of Combat','Earn X Personal Arsenal Points in [Tundra Arms League]',1,'2,000,000',0,0,'Rare','Rare Puzzle Fragment'],
  ['Kings of Combat','Earn X Personal Arsenal Points in [Tundra Arms League]',2,null,1,0,null,null],
];

module.exports = MILESTONES;
